KCX/config/routes.rb
KCX::Application.routes.draw do

  resources :ragefests

  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get '/logout', controller: 'sessions', action: 'destroy'

  post "/search", controller: 'costumes', action: 'filter'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/themes/new', controller: 'themes', action: 'new', as: 'new_theme'
  post '/themes', controller: 'themes', action: 'create'

  get '/themes', controller: 'themes', action: 'index', as: 'themes'
  get '/themes/:id', controller: 'themes', action: 'show', as: 'theme'

  get '/themes/:id/edit', controller: 'themes', action: 'edit', as: 'edit_theme'
  put '/themes/:id', controller: 'themes', action: 'update'

  delete '/themes/:id', controller: 'themes', action: 'destroy'

  get '/costumes/new', controller: 'costumes', action: 'new', as: 'new_costume'
  post '/costumes', controller: 'costumes', action: 'create'

  get '/costumes', controller: 'costumes', action: 'index', as: 'costumes'
  get '/costumes/:id', controller: 'costumes', action: 'show', as: 'costume'

  get '/costumes/:id/edit', controller: 'costumes', action: 'edit', as: 'edit_costume'
  put '/costumes/:id', controller: 'costumes', action: 'update'

  delete '/costumes/:id', controller: 'costumes', action: 'destroy', as: 'destroy_costume'













end

KCX/app/models/user.rb
class User < ActiveRecord::Base

  has_many :costume
  has_secure_password

  validates :email, presence: true
  validates :phone, presence: true

end

KCX/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.password = params[:password]
    @user.phone = params[:phone]
    @user.email = params[:email]

    if @user.save
      session["user_id"] = @user.id
      redirect_to costumes_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.name = params[:name]
    @user.password = params[:password]

    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

KCX/app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @user.name %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= text_field_tag :password, @user.password %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :phone %><br />
    <%= text_field_tag :phone %>
  </div>


  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

KCX/app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password %></td>

      <td><%= button_to 'Show', user_url(user), method: 'get' %></td>
      <td><%= button_to 'Edit', edit_user_url(user), method: 'get' %></td>
      <td><%= button_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

KCX/app/views/users/new.html.erb
<div class="row">
  <div class="span12">
    <h2>New User</h2>
<div class="notice"><%= notice %></div>

<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :phone %><br />
    <%= text_field_tag :phone %>
  </div>

  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

KCX/app/views/users/show.html.erb
<h1> User Data for <%= @user.name %> </h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>E-mail Address: </b>
  <%= @user.email %>
</p>
<p>
  <b>Phone Number</b>
  <%= @user.phone %>
</p>