KCX/config/routes.rb
KCX::Application.routes.draw do

  resources :ragefests

  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get '/logout', controller: 'sessions', action: 'destroy'

  post "/search", controller: 'costumes', action: 'filter'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/themes/new', controller: 'themes', action: 'new', as: 'new_theme'
  post '/themes', controller: 'themes', action: 'create'

  get '/themes', controller: 'themes', action: 'index', as: 'themes'
  get '/themes/:id', controller: 'themes', action: 'show', as: 'theme'

  get '/themes/:id/edit', controller: 'themes', action: 'edit', as: 'edit_theme'
  put '/themes/:id', controller: 'themes', action: 'update'

  delete '/themes/:id', controller: 'themes', action: 'destroy'

  get '/costumes/new', controller: 'costumes', action: 'new', as: 'new_costume'
  post '/costumes', controller: 'costumes', action: 'create'

  get '/costumes', controller: 'costumes', action: 'index', as: 'costumes'
  get '/costumes/:id', controller: 'costumes', action: 'show', as: 'costume'

  get '/costumes/:id/edit', controller: 'costumes', action: 'edit', as: 'edit_costume'
  put '/costumes/:id', controller: 'costumes', action: 'update'

  delete '/costumes/:id', controller: 'costumes', action: 'destroy', as: 'destroy_costume'













end

KCX/app/models/theme.rb
class Theme < ActiveRecord::Base

  has_many :ragefests 
  has_many :costumes, :through => :ragefests

end

KCX/app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def index
    @themes = Theme.all
  end

  def show
    @theme = Theme.find_by_id(params[:id])
  end

  def new
    if session["user_id"].blank?
      redirect_to "/themes", notice: "Please sign in first."
    end
  end

  def create
    @theme = Theme.new
    @theme.name = params[:name]

    if @theme.save
      redirect_to themes_url
    else
      render 'new'
    end
  end

  def edit
    if session["user_id"].blank?
      redirect_to "/themes", notice: "Must sign in to edit themes."
    end
    @theme = Theme.find_by_id(params[:id])
  end

  def update
    @theme = Theme.find_by_id(params[:id])
    @theme.name = params[:name]
        if @theme.save
      redirect_to themes_url
    else
      render 'new'
    end
  end

  def destroy
    if session["user_id"].blank?
      redirect_to "/themes", notice: "Must sign in to destroy themes."
    else
    @theme = Theme.find_by_id(params[:id])
    @theme.destroy
    redirect_to themes_url
    end
  end
end

KCX/app/views/themes/edit.html.erb
<h1>Editing <%= @theme.name %> Theme </h1>


<%= form_tag(theme_url(@theme), method: 'put') do %>
<p> 
	<%= label_tag :name, "Theme Name" %>
	<%= text_field_tag :name, @theme.name, size: 80, placeholder: "What's in a name?" %>
</p>
  
  <div>
    <%= submit_tag "Update Theme" %>
  </div>

<% end %>

KCX/app/views/themes/index.html.erb
<div class="row">
  <div class="span12">
    <h2>Themes</h2>
<div class="notice"><%= notice %></div>
<p><%= link_to 'Add a New Theme', new_theme_url %></p>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @themes.each do |theme| %>
    <tr>

      <td><%= link_to theme.name, theme_url(theme) %></td>
      <td>
      <%= link_to 'Edit', edit_theme_url(theme), :class => 'btn btn-mini' %>
      <%= button_to 'Destroy', theme_url(theme), method: 'delete', data: { confirm: "Do you really want to delete this theme?" }, :class => 'btn btn-mini btn-danger' %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>


KCX/app/views/themes/new.html.erb
<div class="row">
  <div class="span12">
<h2>Add a New Theme</h2>


<%= form_tag(themes_url) do %>
<p>
  <%= label_tag :name %>
  <%= text_field_tag :name, "", size: 80, placeholder: "Theme name..." %>
</p>



  <div>
    <%= submit_tag "Create Theme" %>
  </div>
<% end %>

KCX/app/views/themes/show.html.erb
<h2> <%= @theme.name %> Theme</h2>

<% if @theme.costumes.find(:all).empty? %>
  <h3> No costumes assigned to this theme yet.</h3>
  <% else %>
  <h3> Oh we've got the perfect costume for that </h3>

  <ul>
	 <% @theme.costumes.each do |costume| %>
	 <li><%= link_to costume.name, costume_url(costume) %></li>
	 <% end %>
<% end %>
</ul>