KCX/config/routes.rb
KCX::Application.routes.draw do

  resources :ragefests

  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get '/logout', controller: 'sessions', action: 'destroy'

  post "/search", controller: 'costumes', action: 'filter'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/themes/new', controller: 'themes', action: 'new', as: 'new_theme'
  post '/themes', controller: 'themes', action: 'create'

  get '/themes', controller: 'themes', action: 'index', as: 'themes'
  get '/themes/:id', controller: 'themes', action: 'show', as: 'theme'

  get '/themes/:id/edit', controller: 'themes', action: 'edit', as: 'edit_theme'
  put '/themes/:id', controller: 'themes', action: 'update'

  delete '/themes/:id', controller: 'themes', action: 'destroy'

  get '/costumes/new', controller: 'costumes', action: 'new', as: 'new_costume'
  post '/costumes', controller: 'costumes', action: 'create'

  get '/costumes', controller: 'costumes', action: 'index', as: 'costumes'
  get '/costumes/:id', controller: 'costumes', action: 'show', as: 'costume'

  get '/costumes/:id/edit', controller: 'costumes', action: 'edit', as: 'edit_costume'
  put '/costumes/:id', controller: 'costumes', action: 'update'

  delete '/costumes/:id', controller: 'costumes', action: 'destroy', as: 'destroy_costume'













end

KCX/app/models/costume.rb

class Costume < ActiveRecord::Base

require 'open-uri'

  has_many :ragefests
  has_many :themes, :through => :ragefests
  belongs_to :user
  attr_accessible :theme_ids, :theme_names
  accepts_nested_attributes_for :ragefests, :allow_destroy => true

  validates :image_remote_url, :format => URI::regexp(%w(http https))

  validates_format_of :image_remote_url,
    :with => %r{\.(gif|jpe?g|png)$}i,
    :message => "must have an image extension"

end

KCX/app/controllers/costumes_controller.rb
class CostumesController < ApplicationController

  def index
    @costumes = Costume.all
  end

  def show
    @costume = Costume.find_by_id(params[:id])
  end

  def new
    if session["user_id"].blank?
      redirect_to "/costumes", notice: "Please sign in first."
    end
    @costume = Costume.new
  end

  def create
    @costume = Costume.new
    @costume.name = params[:name]
    @costume.description = params[:description]
    @costume.price = params[:price]
    @costume.currency = params[:currency]
    @costume.user_id = session["user_id"]
    @costume.image_remote_url = params[:image_remote_url]
    @costume.attributes = {'theme_ids' =>[]}.merge(params[:costume]||{})
    if @costume.save
      redirect_to costumes_url
    else
      render 'new'
    end
  end

  def filter
    search_term = params["term"]
    @costumes = Costume.where("name LIKE ?", "%#{search_term}%")
    render 'index'
  end

  def edit
    if session["user_id"].blank?
      redirect_to "/costumes", notice: "Must sign in to edit costumes."
    end
    @costume = Costume.find_by_id(params["id"])
  end

  def update
    @costume = Costume.find_by_id(params["id"])
    @costume.price = params[:price]
    @costume.currency = params[:currency]
    @costume.name = params[:name]
    @costume.description = params[:description]
    @costume.attributes = {'theme_ids' =>[]}.merge(params[:costume]||{})
    @costume.image_remote_url = params[:image_remote_url]
    @costume.save
      redirect_to costumes_url
  end

  def destroy
    if session["user_id"].blank?
      redirect_to "/costumes", notice: "Must sign in to destroy costumes."
    else
    @costume = Costume.find_by_id(params[:id])
    @costume.destroy
    redirect_to costumes_url
    end
  end
end

KCX/app/views/costumes/edit.html.erb
<div class="row">
  <div class="span12">
  <h2>Editing <%= @costume.name %> Costume</h2>
  <div class="row-fluid">
  <div class="span6">
  <% @costume.errors.each do |attr, msg| %>
    <%= "#{attr} #{msg}" if @costume.errors[attr].first == msg %>
  <% end %>

  <%= form_tag(costume_url(@costume), method: 'put') do %>
   <p>
    <%= label_tag :name, "Costume Name" %>
    <%= text_field_tag :name, @costume.name, size: 80, placeholder: "What's in a name?" %>
  </p>
  <p>
    <%= label_tag :description, "Costume Description" %>
    <%= text_field_tag :description, @costume.description, size: 160, placeholder: "Change it if you dare" %>
  </p>
  <p>
    <%= label_tag :price, "Costume Price" %>
    <%= text_field_tag :price, @costume.price, size: 80, placeholder: "You wanted how much?!" %>
  </p>
  <p>
    <%= label_tag :currency, "Costume Currency" %>
    <%= text_field_tag :currency, @costume.currency, size: 80, placeholder: "Lets keep it PG..." %>
  </p>
  </div>
  <div class="span6">

  <p>
    <%= label_tag :image_remote_url, "Enter Image URL" %>
    <%= text_field_tag :image_remote_url, "", size:80, placeholder: "Just a lil copy paste action" %>
  </p>
  <%= label_tag :theme_id, "Themes it goes with" %>

  <% Theme.all.each do |theme| -%>
  <div>
    <%= check_box_tag :theme_ids, theme.id, @costume.themes.include?(theme), :name =>'costume[theme_ids][]'  -%>
    <%= label_tag :theme_ids, theme.name -%>
  </div>
  <% end %>

  <div>
    <%= submit_tag "Update Costume" %>
  </div>
  <% end %>
</div>


KCX/app/views/costumes/index.html.erb
<div class="row">
  <div class="span12">
    <h2>Costumes</h2>
    <p>We know the feeling, you're either desperately looking for the perfect costume, or you're trying to recoup the thousands you've spent on Amazon Prime shipments... either way, we're here to help. Check out your classmates offerings below, and feel free to add some of your own!</p>
               <div class="notice"><%= notice %></div>
                  <%= form_tag '/search' do %>
                  <form class="navbar-search pull-left">
                    <%= text_field_tag :term, "", placeholder: 'Search' %>
                  </form>
                  <% end %>

<p><%= link_to 'Add a New Costume', new_costume_url %></p>

<table class="table table-striped">
  <table style="table-laout: fixed; width: 100%">
  <thread>
    <tr>
      <th align="left">Name</th>
      <th align="left">Description</th>
      <th align="left">Price</th>
      <th align="left">Currency</th>
      <th align="left">Actions</th>
    </tr>
  </thread>
  <tbody>
  <% @costumes.each do |costume| %>
    <tr>
      <td width="10%"><%= link_to costume.name, costume_url(costume) %></td>
      <td style="word-wrap: break-word" width="60%"><%= costume.description %></td>
      <td width="6%"><%= costume.price %></td>
      <td width="10"><%= costume.currency %></td>
      <td width="14">
          <%= link_to 'Edit', edit_costume_url(costume), :class => 'btn btn-mini' %>
          <%= button_to 'Destroy', costume_url(costume), method: 'delete', data: {confirm: "Do you really want to delete this costume?"}, :class => 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>



KCX/app/views/costumes/new.html.erb
<div class="row">
  <div class="span12">
<h2>Add a New Costume</h2>

 <div class="row-fluid">
  <div class="span6">
  <% @costume.errors.each do |attr, msg| %>
  <%= "#{attr} #{msg}" if @costume.errors[attr].first == msg %>
  <% end %>
<%= form_tag "/costumes", :html => {:multipart => true} do %>
 <p>
    <%= label_tag :name, "Costume Name" %>
    <%= text_field_tag :name, "", size: 80, placeholder: "Costume name..." %>
  </p>
  <p>
    <%= label_tag :description, "Description" %>
    <%= text_field_tag :description, "", size: 80, placeholder: "Enter costume description..." %>
  </p>

  <p>
    <%= label_tag :price, "Price" %>
    <%= number_field_tag :price, value = nil, options = {} %>
  </p>
  <p>
    <%= label_tag :currency, "Currency" %>
    <%= text_field_tag :currency, "", size: 80, placeholder: "Are we talking $? Beer? IOUs? You decide..." %>
  </p>
</div>
<div class="span6">
    <p>
    <%= label_tag :image_remote_url, "Enter Image URL" %>
    <%= text_field_tag :image_remote_url, "", size:80, placeholder: "Just a lil copy paste action" %>
  </p>


<%= label_tag :theme_id, "Themes it goes with" %>
<% Theme.all.each do |theme| -%>
  <div>
    <%= check_box_tag :theme_ids, theme.id, @costume.themes.include?(theme), :name =>'costume[theme_ids][]'  -%>
    <%= label_tag :theme_ids, theme.name -%>
  </div>

  <% end %>

 <div>
  <%= submit_tag "Submit"-%>
 </div>
<% end %>
</div>



KCX/app/views/costumes/show.html.erb
<div class="row">
  <div class="span12"><h2> <%= @costume.name %> Costume</h2></div>
</div>
  <div class="row-fluid">
    <div class="span6"><%= image_tag(@costume.image_remote_url, :size => "250x250", :style => "float :left") %></div>
    <div class="span6">
    <p>
  	<b>Description</b>
  	<%= @costume.description %>
    </p>
    <p>
  	<b>Price</b>
  	<%= @costume.price %>
    </p>
    <p>
	  <b>Currency</b>
	  <%= @costume.currency %>
    </p>
    <p>
	  <b>Themes it works for</b>

    <% @costume.themes.each do |f| %>
    <li><%= f.name %></li>
    <% end %>
    </p>
    <p>
    <b>Owner</b>
    <%= @costume.user.name %>
    </p>

    <p>
    <b>Contact the Owner:</b>
      <li><address>
      <a href="mailto: <%= @costume.user.email %>"><%= @costume.user.email %></a>
      </address></li>
    </p>

    <p>
      <li>Phone #:</b>
      <%= @costume.user.phone %></li>
    </p>
    </div>
  </div>
</div>
</div>
