KCX/config/routes.rb
KCX::Application.routes.draw do

  resources :ragefests

  get '/login', controller: 'sessions', action: 'new'
  post '/sessions', controller: 'sessions', action: 'create'
  get '/logout', controller: 'sessions', action: 'destroy'

  post "/search", controller: 'costumes', action: 'filter'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

  get '/themes/new', controller: 'themes', action: 'new', as: 'new_theme'
  post '/themes', controller: 'themes', action: 'create'

  get '/themes', controller: 'themes', action: 'index', as: 'themes'
  get '/themes/:id', controller: 'themes', action: 'show', as: 'theme'

  get '/themes/:id/edit', controller: 'themes', action: 'edit', as: 'edit_theme'
  put '/themes/:id', controller: 'themes', action: 'update'

  delete '/themes/:id', controller: 'themes', action: 'destroy'

  get '/costumes/new', controller: 'costumes', action: 'new', as: 'new_costume'
  post '/costumes', controller: 'costumes', action: 'create'

  get '/costumes', controller: 'costumes', action: 'index', as: 'costumes'
  get '/costumes/:id', controller: 'costumes', action: 'show', as: 'costume'

  get '/costumes/:id/edit', controller: 'costumes', action: 'edit', as: 'edit_costume'
  put '/costumes/:id', controller: 'costumes', action: 'update'

  delete '/costumes/:id', controller: 'costumes', action: 'destroy', as: 'destroy_costume'













end

KCX/app/models/ragefest.rb
class Ragefest < ActiveRecord::Base

  attr_accessible :costume_id, :party_time, :theme_id
  belongs_to :costume
  belongs_to :theme

 end

KCX/app/controllers/ragefests_controller.rb
class RagefestsController < ApplicationController
  # GET /ragefests
  # GET /ragefests.json
  def index
    @ragefests = Ragefest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ragefests }
    end
  end

  # GET /ragefests/1
  # GET /ragefests/1.json
  def show
    @ragefest = Ragefest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ragefest }
    end
  end

  # GET /ragefests/new
  # GET /ragefests/new.json
  def new
    @ragefest = Ragefest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ragefest }
    end
  end

  # GET /ragefests/1/edit
  def edit
    @ragefest = Ragefest.find(params[:id])
  end

  # POST /ragefests
  # POST /ragefests.json
  def create
    @ragefest = Ragefest.new(params[:ragefest])

    respond_to do |format|
      if @ragefest.save
        format.html { redirect_to @ragefest, notice: 'Ragefest was successfully created.' }
        format.json { render json: @ragefest, status: :created, location: @ragefest }
      else
        format.html { render action: "new" }
        format.json { render json: @ragefest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ragefests/1
  # PUT /ragefests/1.json
  def update
    @ragefest = Ragefest.find(params[:id])

    respond_to do |format|
      if @ragefest.update_attributes(params[:ragefest])
        format.html { redirect_to @ragefest, notice: 'Ragefest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ragefest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ragefests/1
  # DELETE /ragefests/1.json
  def destroy
    @ragefest = Ragefest.find(params[:id])
    @ragefest.destroy

    respond_to do |format|
      format.html { redirect_to ragefests_url }
      format.json { head :no_content }
    end
  end
end

KCX/app/helpers/ragefests_helper.rb
module RagefestsHelper
end

KCX/app/views/ragefests/_form.html.erb
<%= form_for(@ragefest) do |f| %>
  <% if @ragefest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ragefest.errors.count, "error") %> prohibited this ragefest from being saved:</h2>

      <ul>
      <% @ragefest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :costume_id %><br />
    <%= f.number_field :costume_id %>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br />
    <%= f.number_field :theme_id %>
  </div>
  <div class="field">
    <%= f.label :party_time %><br />
    <%= f.datetime_select :party_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

KCX/app/views/ragefests/edit.html.erb
<h1>Editing ragefest</h1>

<%= render 'form' %>

<%= link_to 'Show', @ragefest %> |
<%= link_to 'Back', ragefests_path %>

KCX/app/views/ragefests/index.html.erb
<h1>Listing ragefests</h1>

<table>
  <tr>
    <th>Costume</th>
    <th>Theme</th>
    <th>Party time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ragefests.each do |ragefest| %>
  <tr>
    <td><%= ragefest.costume_id %></td>
    <td><%= ragefest.theme_id %></td>
    <td><%= ragefest.party_time %></td>
    <td><%= link_to 'Show', ragefest %></td>
    <td><%= link_to 'Edit', edit_ragefest_path(ragefest) %></td>
    <td><%= link_to 'Destroy', ragefest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ragefest', new_ragefest_path %>

KCX/app/views/ragefests/new.html.erb
<h1>New ragefest</h1>

<%= render 'form' %>

<%= link_to 'Back', ragefests_path %>

KCX/app/views/ragefests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Costume:</b>
  <%= @ragefest.costume_id %>
</p>

<p>
  <b>Theme:</b>
  <%= @ragefest.theme_id %>
</p>

<p>
  <b>Party time:</b>
  <%= @ragefest.party_time %>
</p>


<%= link_to 'Edit', edit_ragefest_path(@ragefest) %> |
<%= link_to 'Back', ragefests_path %>